In [ ]:
import numpy as np

d1ary = np.array([1,2,3])
d2ary = np.array([[1,2],[3,4]])
d3ary = np.array([[[1,2],[3,4]],
                 [[4,5],[6,7]]])
print(d1ary)
print(d2ary)
print(d3ary)

d1 = np.array(range(1,9))
d2 = np.array(range(1,9)).reshape(2,4)
d3 = np.array(range(1,9)).reshape(2,2,2)
print(d1)
print(d2)
print(d3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
d3.shape, d3.ndim, d3.size

((2, 2, 2), 3, 8)

In [39]:
import pandas as pd

student = [['이름',	'키',	'몸무게',	'성별',	'나이'],
['홍일동',	'166',	'90',	'남',	'19'],
['홍이동',	'168',	'60',	'여',	'20'],
['홍삼동',	'170',	'50',	'남',	'21'],
['홍사동',	'172',	'70',	'여',	'22'],
['홍오동',	'174',	'45.3',	'남',	'23']]

df = pd.DataFrame(student[1:], columns=student[0])
df


이름    키   몸무게 성별  나이
0  홍일동  166    90  남  19
1  홍이동  168    60  여  20
2  홍삼동  170    50  남  21
3  홍사동  172    70  여  22
4  홍오동  174  45.3  남  23

In [40]:
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('C:\AI_X_심화MBC\student.csv')

df['키'] = pd.to_numeric(df['키'])
df['몸무게'] = pd.to_numeric(df['몸무게'])
df['나이'] = pd.to_numeric(df['나이'])
df


이름    키   몸무게 성별  나이
0  홍일동  166  90.0  남  19
1  홍이동  168  60.0  여  20
2  홍삼동  170  50.0  남  21
3  홍사동  172  70.0  여  22
4  홍오동  174  45.3  남  23

In [41]:
df.describe()

키        몸무게         나이
count    5.000000   5.000000   5.000000
mean   170.000000  63.060000  21.000000
std      3.162278  17.813422   1.581139
min    166.000000  45.300000  19.000000
25%    168.000000  50.000000  20.000000
50%    170.000000  60.000000  21.000000
75%    172.000000  70.000000  22.000000
max    174.000000  90.000000  23.000000

In [44]:
from numpy import corrcoef


cr = corrcoef(df['키'], df['몸무게'])
cr

array([[ 1.        , -0.70476309],
       [-0.70476309,  1.        ]])

In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df.columns

Index(['이름', '키', '몸무게', '성별', '나이'], dtype='object')

In [47]:
df.키

0    166
1    168
2    170
3    172
4    174
Name: 키, dtype: int64

In [49]:
df['몸무게'], type(df['몸무게'])

(0    90.0
 1    60.0
 2    50.0
 3    70.0
 4    45.3
 Name: 몸무게, dtype: float64,
 pandas.core.series.Series)

In [50]:
height = df['키']
height.describe()

count      5.000000
mean     170.000000
std        3.162278
min      166.000000
25%      168.000000
50%      170.000000
75%      172.000000
max      174.000000
Name: 키, dtype: float64

In [56]:
from statistics import covariance
import numpy as np


cr = covariance(df['키'], df['몸무게'])/np.sqrt(df['키'].var() * df['몸무게'].var())
cr

np.float64(-0.7047630925231074)

In [58]:
weight = df['몸무게']
weight.var(), weight.std()

(317.31800000000004, 17.813421905967424)